/**
 * Example content spec for docx-master.
 * Export: { meta, build(helpers, brand, contentWidthDxa) }
 */
export const meta = {
  title: 'Atelier · Deck Spec Example',
  filename: 'atelier-deck-spec-example',
};

/**
 * @param {typeof import('../lib/docx-helpers.mjs')} h
 * @param {import('../lib/brand.mjs').BrandTokens} brand
 * @param {number} contentWidthDxa
 */
export function build(h, brand, contentWidthDxa) {
  const { H1, H2, P, B, B2, TBL, deckPage, runs } = h;

  const pages = [
    {
      kicker: 'Slide 01',
      title: '存量博弈 · 餐饮单店',
      body: 'CCFA 2025 教学模型：77.2% 门店毫无增长，45.7% 在下滑。',
      bullets: ['同街五十米 · 两种结局', '模型更换 > 拼命努力'],
    },
    {
      kicker: 'Slide 02',
      title: '营收公式 · 五块木板',
      body: '场景 → 品类 → 门店 · 客单价与加购结构决定毛利天花板。',
      bullets: ['流量', '转化', '客单价', '复购', '成本'],
    },
    {
      kicker: 'Slide 03',
      title: '标杆 · 南城香',
      body: '三元早餐 · 转化工程：日流 5000→8000+，午餐人均 ~30 元。',
    },
  ];

  const children = [
    H1(meta.title, brand),
    P('Generated by docx-master · brand-driven · validate + preview pipeline', brand, { after: 320 }),
    H2('Executive summary', brand),
    P('本示例演示 deckPage 工厂、双层 bullets、双宽表格与 CJK 混排。', brand),
    B('Read skills/tableai-docx-master/SKILL.md before generating.', brand),
    B2('Nested bullet level via numbering config, never unicode •', brand),
    ...pages.flatMap((p) => deckPage(p, brand)),
    H2('Key metrics', brand),
    TBL(
      [
        ['指标', '数值', '来源'],
        ['无增长门店', '77.2%', 'CCFA 2025'],
        ['下滑门店', '45.7%', 'CCFA 2025'],
        ['SKU 优化案例', '86 → 41', '教学模型'],
      ],
      [Math.floor(contentWidthDxa * 0.4), Math.floor(contentWidthDxa * 0.25), contentWidthDxa - Math.floor(contentWidthDxa * 0.65)],
      brand,
      contentWidthDxa,
    ),
    P('', brand, { after: 240 }),
    H2('Appendix · Q&A', brand),
    new h.Paragraph({
      numbering: { reference: 'numbered', level: 0 },
      spacing: { after: 120 },
      children: [
        new h.TextRun({
          text: '如何验证表格不溢出？',
          font: { name: brand.fonts.latin, eastAsia: brand.fonts.eastAsia },
          size: brand.bodySize,
          color: brand.colors.ink,
        }),
      ],
    }),
    new h.Paragraph({
      numbering: { reference: 'numbered', level: 0 },
      spacing: { after: 120 },
      children: [
        new h.TextRun({
          text: '运行 pnpm docx:build 并查看 page PNG。',
          font: { name: brand.fonts.latin, eastAsia: brand.fonts.eastAsia },
          size: brand.bodySize,
          color: brand.colors.ink,
        }),
      ],
    }),
  ];

  return children;
}
